create table if not exists public.enquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  company text not null,
  designation text not null,
  phone text not null,
  location text not null,
  services text[] not null default '{}',
  employees text,
  details text,
  status text not null default 'new' check (status in ('new', 'contacted', 'closed'))
);

alter table public.enquiries enable row level security;

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.admin_users enable row level security;

drop policy if exists "Anyone can submit an enquiry" on public.enquiries;
create policy "Anyone can submit an enquiry"
on public.enquiries for insert
to anon, authenticated
with check (status = 'new');

drop policy if exists "Authenticated staff can read enquiries" on public.enquiries;
create policy "Authenticated staff can read enquiries"
on public.enquiries for select
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

drop policy if exists "Authenticated staff can update enquiries" on public.enquiries;
create policy "Authenticated staff can update enquiries"
on public.enquiries for update
to authenticated
using (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1 from public.admin_users
    where admin_users.user_id = auth.uid()
  )
);

create index if not exists enquiries_created_at_idx
on public.enquiries (created_at desc);
